// Generated by CoffeeScript 1.3.1
var Antikythera;

Antikythera = (function() {

  Antikythera.name = 'Antikythera';

  Antikythera.prototype.currentStage = {
    name: "default"
  };

  function Antikythera(options) {
    this.options = options;
    this.stages = {};
    this.stageQueue = [];
    this.currentStage = this.currentStage;
  }

  Antikythera.prototype.go = function(name, data) {
    var _ref;
    if ((_ref = this.options) != null ? _ref.development : void 0) {
      return this.stageQueue.push({
        name: name,
        data: data
      });
    }
    if (!(name != null) || name === this.currentStage.name) {
      return false;
    }
    return this._transition(this.stages[name], data);
  };

  Antikythera.prototype.stage = function(name, transitionIn, transitionOut) {
    return this.stages[name] = {
      name: name,
      transitionIn: transitionIn,
      transitionOut: transitionOut
    };
  };

  Antikythera.prototype.crank = function() {
    var stage;
    if (!(this.stageQueue.length > 0)) {
      return false;
    }
    stage = this.stageQueue.shift();
    return this._transition(this.stages[stage.name], stage.data);
  };

  Antikythera.prototype._transition = function(stage, data) {
    var _base;
    if (typeof (_base = this.currentStage).transitionOut === "function") {
      _base.transitionOut(data != null ? data.out : void 0);
    }
    this.currentStage = stage;
    if (typeof stage.transitionIn === "function") {
      stage.transitionIn(data != null ? data["in"] : void 0);
    }
    return true;
  };

  return Antikythera;

})();
